name: "Fix code styling"

on:
  workflow_call:
    inputs:
      php:
        default: "8.3"
        type: string
      message:
        default: Fix code styling
        type: string
      fix:
        default: true
        type: boolean

jobs:
  php-code-styling:
    name: Fix code styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2, php-cs-fixer
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --diff --allow-risky=yes

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ${{ inputs.message }}