name: "Normalize composer.json files"

on:
  workflow_call:
    inputs:
      php:
        default: "8.3"
        type: string
      message:
        default: Normalize composer.json files
        type: string
      fix:
        default: true
        type: boolean

jobs:
  normalize:
    name: "Normalize composer.json files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Normalize composer.json file
        run: |
          composer global config --no-plugins allow-plugins.ergebnis/composer-normalize true
          composer global require ergebnis/composer-normalize
          composer normalize

      - name: Commit normalized files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}